### ISSUE TITLE
LSP Umbrella

### ISSUE THREAD

**Issue by thymikee** [flowtype/flow-for-vscode#243]
We're going to track LSP (Language Server Protocol) related stuff, so we can reach feature parity with current extension.

* [x] Monorepo support (Yarn workspaces)
* [x] VSCode workspaces support
* [x] Coverage with flow status
* [ ] Go To Reference of values that are imported from modules without `@flow` (not sure if possible yet)
* [x] Make use of `relatedInformation` for richer diagnostics with Flow >=0.67 (PR #258).
* Integrate with current options
	* [ ] `runOnEdit`
	* [ ] `runOnAllFiles`

Nice to haves, but not sure if possible with `@builtin` TS disabled:
* [x] Intellisense features could we support through LSP? Right now, without the TS `@builtin`, there's no support for Rename Symbol, for instance.
* [x] Apparently the TS builtin extension is what provides inline documentation when hovering over values that have doc-block comments (i.e. `/** foo */`). Maybe this should just be broken out from the main TS `@builtin` so you can disable other TS features but keep the doc-block parsing feature? Otherwise I'm guessing `flow-for-vscode` would have to reimplement this.

cc @wbinnssmith @kpsroka @jslauthor @orta

**Comment by jslauthor** [comment]
> Intellisense features could we support through LSP? Right now, without the TS @builtin, there's no support for Rename Symbol, for instance.

😬 I wasn't aware of this limitation. Is there a way around this somehow? Intellisense was a big part of why we wanted to support this.

**Comment by minedeljkovic** [comment]
Please add displaying flow status to the list (current extension supports that feature).
I find it essential for any large codebase where flow recheck is not instant.

**Comment by orta** [comment]
Features like rename symbol work through the LSP for TS, so if there's a way to track IDs through flows internals then it should be feasible

**Comment by namuol** [comment]
Related issue in the `flow` repo regarding supporting `documentation` fields in LSP: https://github.com/facebook/flow/issues/7725

**Comment by goodmind** [comment]
Is this issue tracks usage with builtin extension disabled?

**Comment by Mayank1791989** [comment]
You can create a separate issue for it.

**Comment by mroch** [comment]
jsdoc support was implemented upstream. I just checked that box off
